### ISSUE TITLE
Controlar traçado da água

### ISSUE THREAD

**Issue by eduardovra** [fabiokr/pipemania#18]
Determinar por onde o fluxo da agua vai passar. Acho que pra facilitar da pra determinar isso no momento em que a agua começa a fluir pelo cano, da pra assumir a primeira conexão válida que for encontrada. A partir desse ponto o cano não poderá mais ser alterado.

**Comment by eduardovra** [comment]
Tava pensando o que tu acha de usar os canos abertos somente onde o fluxo ta passando ou ja passou ? Assim fica mais vizual pro cara que os canos fechados são os que ele ainda pode mudar.

**Comment by fabiokr** [comment]
Hmm acho que ficaria meio estranho graficamente, daria a impressão que não é uma conexão válida.
