### ISSUE TITLE
#40 causa tela preta e nada acontece

### ISSUE THREAD

**Issue by fabiokr** [fabiokr/pipemania#41]
Não tinha testado no meu PC o PR #40 antes. Atualizei meu master agora, fui abrir o game e só abre uma tela preta e nada acontece. Revertendo o commit do PR faz o jogo rodar novamente.

**Comment by eduardovra** [comment]
Muito estranho, testei no Ubuntu e funcionou.
Mas pode ter alguma variável não inicializada ou algo assim. Vou investigar melhor.
