### ISSUE TITLE
Agua fluindo continuamente

### ISSUE THREAD

**Issue by fabiokr** [fabiokr/pipemania#7]
Começando do ponto inicial, fazer a água fluir dentre os canos que montam uma sequência válida.

**Comment by eduardovra** [comment]
Podemos usar esse issue para aprimorar a passagem do fluxo de agua, levando em conta por onde a agua entrou e por onde vai sair.
Esse issue vai depender da implementação do #18

**Comment by eduardovra** [comment]
Resolvido em #20
